print('hola Fundamentos')
print(2 + 3)
print('2' + '3')
print(2* (3+5))
print(2 * 3 + 5)
print(3 * 'Hola')
print('Hola' * 3)
## Se comentan las siguientes instrucciones para que no de error
#PRINT('hola')
#print(hola)
